services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    restart: always
    ports:
      - "5173:5173"
    container_name: keylab_client

  db:
    image: mariadb:latest
    env_file:
      - ./server/.env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    container_name: keylab_db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - client
    container_name: keylab_server
    restart: always
    env_file:
      - ./server/.env
